class Settings:
    BASE_URL = "https://yakkun.com"
    STATUS_LIST_URL = BASE_URL + "/swsh/stats_list.htm?mode=all"

    STATUS = {
        "HP": "hitpoint",
        "こうげき": "attack",
        "ぼうぎょ": "block",
        "とくこう": "contact",
        "とくぼう": "defense",
        "すばやさ": "speed",
        "合計": "total"
    }

    REGIONS = {
        1: "カントー",
        2: "ジョウト",
        3: "ホウエン",
        4: "シンオウ",
        5: "イッシュ",
        6: "カロス",
        7: "アローラ",
        8: "ガラル",
    }

    COLUMNS = [
        "No.",
        "なまえ",
        "タイプ1",
        "タイプ2",
        "とくせい1",
        "とくせい2",
        "ゆめとくせい",
        "HP",
        "こうげき",
        "ぼうぎょ",
        "とくこう",
        "とくぼう",
        "すばやさ",
        "合計",
        "最終進化",
        "地方",
    ]

    EXCEPT_POKEMON_URLS = {
        "メガフシギバナ": "https://yakkun.com/sm/zukan/n3m",
        "メガリザードンX": "https://yakkun.com/sm/zukan/n6x",
        "メガリザードンY": "https://yakkun.com/sm/zukan/n6y",
        "メガカメックス": "https://yakkun.com/sm/zukan/n9m",
        "メガスピアー": "https://yakkun.com/sm/zukan/n15m",
        "メガピジョット": "https://yakkun.com/sm/zukan/n18m",
        "メガフーディン": "https://yakkun.com/sm/zukan/n65m",
        "メガヤドラン": "https://yakkun.com/sm/zukan/n80m",
        "メガゲンガー": "https://yakkun.com/sm/zukan/n94m",
        "メガガルーラ": "https://yakkun.com/sm/zukan/n115m",
        "メガカイロス": "https://yakkun.com/sm/zukan/n127m",
        "メガギャラドス": "https://yakkun.com/sm/zukan/n130m",
        "メガプテラ": "https://yakkun.com/sm/zukan/n142m",
        "メガミュウツーX": "https://yakkun.com/sm/zukan/n150x",
        "メガミュウツーY": "https://yakkun.com/sm/zukan/n150y",
        "メガデンリュウ": "https://yakkun.com/sm/zukan/n181m",
        "メガハガネール": "https://yakkun.com/sm/zukan/n208m",
        "メガハッサム": "https://yakkun.com/sm/zukan/n212m",
        "メガヘラクロス": "https://yakkun.com/sm/zukan/n214m",
        "メガヘルガー": "https://yakkun.com/sm/zukan/n229m",
        "メガバンギラス": "https://yakkun.com/sm/zukan/n248m",
        "メガジュカイン": "https://yakkun.com/sm/zukan/n254m",
        "メガバシャーモ": "https://yakkun.com/sm/zukan/n257m",
        "メガラグラージ": "https://yakkun.com/sm/zukan/n260m",
        "メガサーナイト": "https://yakkun.com/sm/zukan/n282m",
        "メガヤミラミ": "https://yakkun.com/sm/zukan/n302m",
        "メガクチート": "https://yakkun.com/sm/zukan/n303m",
        "メガボスゴドラ": "https://yakkun.com/sm/zukan/n306m",
        "メガチャーレム": "https://yakkun.com/sm/zukan/n308m",
        "メガライボルト": "https://yakkun.com/sm/zukan/n310m",
        "メガサメハダー": "https://yakkun.com/sm/zukan/n319m",
        "メガバクーダ": "https://yakkun.com/sm/zukan/n323m",
        "メガチルタリス": "https://yakkun.com/sm/zukan/n334m",
        "メガジュペッタ": "https://yakkun.com/sm/zukan/n354m",
        "メガアブソル": "https://yakkun.com/sm/zukan/n359m",
        "メガオニゴーリ": "https://yakkun.com/sm/zukan/n362m",
        "メガボーマンダ": "https://yakkun.com/sm/zukan/n373m",
        "メガメタグロス": "https://yakkun.com/sm/zukan/n376m",
        "メガラティアス": "https://yakkun.com/sm/zukan/n380m",
        "メガラティオス": "https://yakkun.com/sm/zukan/n381m",
        "ゲンシカイオーガ": "https://yakkun.com/sm/zukan/n382p",
        "ゲンシグラードン": "https://yakkun.com/sm/zukan/n383p",
        "メガレックウザ": "https://yakkun.com/sm/zukan/n384m",
        "メガミミロップ": "https://yakkun.com/sm/zukan/n428m",
        "メガガブリアス": "https://yakkun.com/sm/zukan/n445m",
        "メガルカリオ": "https://yakkun.com/sm/zukan/n448m",
        "メガユキノオー": "https://yakkun.com/sm/zukan/n460m",
        "メガエルレイド": "https://yakkun.com/sm/zukan/n475m",
        "メガタブンネ": "https://yakkun.com/sm/zukan/n531m",
        "メガディアンシー": "https://yakkun.com/sm/zukan/n719m",
    }
